imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources: ['bootstrap_3_layout.html.twig']

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        ["BankrotSiteBundle", "FOSUserBundle"]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        closure:
            jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        mappings:
            translatable:
                type: annotation
                alias: Gedmo
                prefix: Gedmo\Translatable\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Bankrot\SiteBundle\Entity\User
    registration:
        form:
            type: bankrot_site_user_registration
        confirmation:
            enabled:    true
#                template:   BankrotSiteBundle:Mail:confirm.html.twig
            from_email:
                address: isbankrot@gmail.com
                sender_name: Bankrot.ru
    profile:
        form:
            type: bankrot_site_user_profile_edit
    service:
        mailer:  fos_user.mailer.twig_swift

#stof_doctrine_extensions:
#    default_locale: %locale%
#    uploadable:
#        default_file_path: %kernel.root_dir%/../web/uploads
#        mime_type_guesser_class: Stof\DoctrineExtensionsBundle\Uploadable\MimeTypeGuesserAdapter
#        default_file_info_class: Stof\DoctrineExtensionsBundle\Uploadable\UploadedFileInfo
#    orm:
#        default:
#            timestampable: true
#            uploadable: true

iphp_file_store:
    mappings:
        files:
            namer:
                translit: ~
                propertyPrefix:    #propertyPostfix - для того чтобы добавить строку в конец файла
                    params: { field : id, delimiter: "_" }
            upload_dir:  %kernel.root_dir%/../web/upload
            upload_path: /upload
        arbitrationFiles:
            namer:
                translit: ~
                propertyPrefix:    #propertyPostfix - для того чтобы добавить строку в конец файла
                    params: { field : id, delimiter: "_" }
            upload_dir:  %kernel.root_dir%/../web/upload/arbitrations
            upload_path: /upload

knp_paginator:
    page_range: 20                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: id          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: BankrotSiteBundle::pagination.html.twig
