bankrot_admin:
    resource: "@BankrotAdminBundle/Controller/"
    type:     annotation
    prefix:   /

bankrot_site:
    resource: "@BankrotSiteBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"


fos_user_change_password:
    resource: @FOSUserBundle/Resources/config/routing/change_password.xml

fos_user_profile:
    resource: @FOSUserBundle/Resources/config/routing/profile.xml
    prefix: /profile

fos_user_registration:
    resource: @FOSUserBundle/Resources/config/routing/registration.xml

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: @FOSUserBundle/Resources/config/routing/resetting.xml

fos_user_security:
    resource: @FOSUserBundle/Resources/config/routing/security.xml

fos_js_routing:
    resource: @FOSJsRoutingBundle/Resources/config/routing/routing.xml
