services:
    bankrot_site.menu_builder:
        class: Bankrot\SiteBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]

    bankrot_site.main_menu:
        class: Knp\Menu\MenuItem
        factory_service: bankrot_site.menu_builder
        factory_method: createMainMenu
        arguments: ["@request_stack"]
        tags:
            - { name: knp_menu.menu, alias: main }

    bankrot_site.auth_menu:
        class: Knp\Menu\MenuItem
        factory_service: bankrot_site.menu_builder
        factory_method: createAuthMenu
        arguments: ["@request_stack"]
        tags:
            - { name: knp_menu.menu, alias: auth }

    bankrot_site.auth_logged_menu:
        class: Knp\Menu\MenuItem
        factory_service: bankrot_site.menu_builder
        factory_method: createAuthLoggedMenu
        arguments: ["@request_stack"]
        tags:
            - { name: knp_menu.menu, alias: auth_logged }

    bankrot_site.registration.form.type:
        class: Bankrot\SiteBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: bankrot_site_user_registration }